// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockStore.WebApp.Data;

namespace StockStore.WebApp.Migrations
{
    [DbContext(typeof(StockStoreContext))]
    [Migration("20220618070622_ChangeSeedDataInStockStoreContext")]
    partial class ChangeSeedDataInStockStoreContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockStore.WebApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "لپ تاپ",
                            Name = "لپ تاپ"
                        },
                        new
                        {
                            Id = 2,
                            Description = "موبایل",
                            Name = "موبایل"
                        },
                        new
                        {
                            Id = 3,
                            Description = "ساعت هوشمند",
                            Name = "ساعت هوشمند"
                        },
                        new
                        {
                            Id = 4,
                            Description = "مانیتور",
                            Name = "مانیتور"
                        });
                });

            modelBuilder.Entity("StockStore.WebApp.Models.CategoryToProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryToProducts");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2
                        });
                });

            modelBuilder.Entity("StockStore.WebApp.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price")
                        .HasColumnType("Money");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 854.0m,
                            QuantityInStock = 5
                        },
                        new
                        {
                            Id = 2,
                            Price = 3302.0m,
                            QuantityInStock = 8
                        },
                        new
                        {
                            Id = 3,
                            Price = 2500m,
                            QuantityInStock = 3
                        },
                        new
                        {
                            Id = 4,
                            Price = 4500m,
                            QuantityInStock = 3
                        });
                });

            modelBuilder.Entity("StockStore.WebApp.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinaly")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("StockStore.WebApp.Models.OrderDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("DetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("StockStore.WebApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "لپ‌تاپ‌های سری X‌ «ایسوس» به‌نسبت کارایی و کیفیت، قیمت مناسبی دارند و جزو پرطرفدارترین محصولات این شرکت هستند. این محصولات معمولاً با مشخصات سخت‌افزاری مختلف و در طرح‌ها و رنگبندی‌های متنوعی عرضه می‌شوند تا پاسخ‌گوی نیاز کاربران مختلف باشند. یکی از این محصولات X543MA-GQ1012 است که مثل مدل‌های قبلی تماما از پلاستیک ساخته شده است؛ اما کیفیت و استحکام آن حس بدنه‌ی آلومینیومی را القا می‌کند. این لپ‌تاپ با وجود ضخامت بدنه‌ی تقریبا زیاد 27میلی‌متری، فقط حدود 2 کیلوگرم وزن دارد",
                            ItemId = 1,
                            Name = "لپ تاپ 15.6 اینچی ایسوس مدل X543MA-GQ1012"
                        },
                        new
                        {
                            Id = 2,
                            Description = " IdeaPad 3 15IGL05 – Z یک سیستم با ظاهری خشک است. سیستمی که در طراحی آن در عین شیک بودن ظاهری بسیار خشک و بی روح را می‌توان مشاهده کرد. البته شاید این موضوع در رنگ‌های نقره‌ای و مشکی دیده شود و رنگ زرشکی این حس را کمتر منتقل کند. در ظاهر این سیستم می‌توان کیبورد این محصول را مشاهده کرد که با کلیدهای نرم پوشیده شده‌است. شاید این کیبورد back lit  نداشته باشد اما این موضوع به هیچ عنوان از قابلیت‌های خاص آن کم نمی‌کند. یکی از قابلیت‌های آن همان استاندارد بودن این کیبورد بوده که برای استفاده بسیار نرم و راحت است اما باید در نظر گرفت در زمان بازی شاید نتوان گفت کیبورد مناسبی است زیرا کیبوردهای مناسب برای بازی مقداری سخت‌تر هستند تا به راحتی زیر انگشت دست حس شوند. از دیگر موارد ظاهری می‌توان به وب‌کم این محصول توجه داشت که در بالای لپ‌تاپ قرار گرفته است و به راحتی قابل استفاده است.",
                            ItemId = 2,
                            Name = "لپ تاپ 15.6 اینچی لنوو مدل IdeaPad 3 15IGL05 - Z"
                        },
                        new
                        {
                            Id = 3,
                            Description = "سری لپ‌تاپ‌های مک‌بوک شرکت اپل تا به امروز بدون هیچ تعریف اضافی توانسته‌اند با بهره بردن از مشخصات فنی قدرتمند، عملکرد بسیار خوب و قابل قبولی را ارائه کنند. یکی از لپ‌تاپ‌های قدرتمند این سری، مدل MacBook Pro Mk183 2021 است. این لپ‌تاپ به صفحه‌نمایش با ابعاد 16.2 اینچی با رزولوشن 2234×3456 پیکسل از نوع Liquid Retina XDR مجهز شده است که توانایی نمایش 254 پیکسل در هر اینچ را دارد.",
                            ItemId = 3,
                            Name = "لپ تاپ 16.2 اینچی اپل مدل MacBook Pro Mk183 2021"
                        },
                        new
                        {
                            Id = 4,
                            Description = "بالاخره بعد از شایعات، شاهد رونمایی جدید‌ترین گوشی‌های هوشمند اپل در قالب خانواده آیفون 13 بودیم. آیفون 13 پرو مکس، آیفون 13 پرو، آیفون 13 و آیفون 13 مینی به‌عنوان جدید‌ترین گوشی‌های هوشمند این شرکت معرفی شدند. آیفون 13 پرو مکس بدون شک به مشخصات فنی قدرتمند‌تری به نسبت ما‌بقی اعضای این خانواده مجهز شده است. از نظر طراحی تفاوت چندانی با نسل قبلی پرچمداران این شرکت شاهد نبودیم. تنها در نمای رو به رویی این بار اپل از ناچ با عرض کمتری به نسبت نسل قبلی بهره برده است.",
                            ItemId = 4,
                            Name = "iPhone 13 Pro Max A2644"
                        });
                });

            modelBuilder.Entity("StockStore.WebApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StockStore.WebApp.Models.CategoryToProduct", b =>
                {
                    b.HasOne("StockStore.WebApp.Models.Category", "Category")
                        .WithMany("categoryToProuducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockStore.WebApp.Models.Product", "product")
                        .WithMany("categoryToProuducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockStore.WebApp.Models.Order", b =>
                {
                    b.HasOne("StockStore.WebApp.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockStore.WebApp.Models.OrderDetail", b =>
                {
                    b.HasOne("StockStore.WebApp.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockStore.WebApp.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockStore.WebApp.Models.Product", b =>
                {
                    b.HasOne("StockStore.WebApp.Models.Item", "Item")
                        .WithOne("Product")
                        .HasForeignKey("StockStore.WebApp.Models.Product", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
